{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"sample_evg_enriquecido\",\"Dim_Calendario\",\"Dim_Curso\",\"Dim_Aluno\",\"Dim_turma\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3a9e7fca-235a-4626-9a03-9d7409fb34c1",
        "fromColumn": "dt_matricula",
        "fromTable": "sample_evg_enriquecido",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0dc8cf17-a3e4-48ac-9adc-4be558576be6"
      },
      {
        "name": "65e8b2e0-db80-480d-a43d-f1682c8e15e5",
        "fromColumn": "dt_fim",
        "fromTable": "sample_evg_enriquecido",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e5b7cfce-ccad-4ec6-acff-3739d4d4d687"
      },
      {
        "name": "3cf1f448-4648-4b7e-825a-116fcc2d35e5",
        "fromColumn": "Data",
        "fromTable": "Dim_Calendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bbaeb3f6-cc6a-4434-a8e4-e5aaba71dfd1"
      },
      {
        "name": "b71677c1-ba5d-47f8-a27d-0f6b21b20f9c",
        "fromColumn": "dt_matricula",
        "fromTable": "Dim_turma",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d8f42845-b91c-4467-8bef-7eb5b34c3e41"
      },
      {
        "name": "AutoDetected_1d9ff0f5-de0d-47bf-aea4-bfdd298c4c9f",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "cod_matricula",
        "fromTable": "Dim_Aluno",
        "toColumn": "cod_matricula",
        "toTable": "sample_evg_enriquecido"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_687634f3-35e9-4c59-89cd-167b1614009f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cbb21eff-d1b2-4ef5-a9b2-930584d2b335",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7726bd16-3caf-4dda-b492-5e67d1587313",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0df4d7b7-5194-4e94-8fc9-b77e0ad5cb7e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0ad1be55-41a0-49dc-8fa6-48efdce8f92c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "542d7948-2a07-4f86-a858-7dedd4cfd164",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "28d38726-4e5e-486c-b927-14f9da728f1c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9e25a6f0-e9e6-44f1-b364-af2d9e8f2811",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "336e6229-be76-476c-acf4-c5126bf7d02a",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "0900f24d-3eab-4c08-b3d6-c42f4bfd33df",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "8355e7ff-14c2-4f08-b40a-edeacc005062",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "c461607f-05f1-4ce5-8da1-e19c40e74796",
                "ordinal": 3
              }
            ],
            "lineageTag": "1fe01bec-962b-4cdd-976d-7df75ef6962b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "279b8cd4-9bef-4a64-81b5-8685ee071cb5",
        "partitions": [
          {
            "name": "DateTableTemplate_687634f3-35e9-4c59-89cd-167b1614009f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "sample_evg_enriquecido",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17b49f90-cb16-463b-b888-49e10bb718c2",
            "sourceColumn": "cod_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "dt_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "687b5d51-db6a-49de-a976-d7376662dbe2",
            "sourceColumn": "dt_matricula",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_0dc8cf17-a3e4-48ac-9adc-4be558576be6"
                },
                "isDefault": true,
                "relationship": "3a9e7fca-235a-4626-9a03-9d7409fb34c1"
              }
            ]
          },
          {
            "name": "nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a71d03a-bd36-4990-9b95-ee4633a0e29c",
            "sourceColumn": "nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f540718-a8b8-4eda-a7c0-d16e9d1c11c5",
            "sourceColumn": "cod_turma",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eb33b90-a2f0-464e-8978-4cd74dd97426",
            "sourceColumn": "nome_turma",
            "summarizeBy": "none"
          },
          {
            "name": "modalidade_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1691bf8-1e53-416d-a2f7-b0b4bb4e7cd4",
            "sourceColumn": "modalidade_turma",
            "summarizeBy": "none"
          },
          {
            "name": "cod_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ff65b652-c42f-46ca-bc65-f887dd31d2bd",
            "sourceColumn": "cod_curso",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d52fd355-7d63-456d-acfe-bf6c78d6a88a",
            "sourceColumn": "nome_curso",
            "summarizeBy": "none"
          },
          {
            "name": "carga_horaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80b3bef2-7f87-4330-aef8-0fc55815b670",
            "sourceColumn": "carga_horaria",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b3fdc6cc-d93d-43d3-8b29-36616acede97",
            "sourceColumn": "dt_fim",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_e5b7cfce-ccad-4ec6-acff-3739d4d4d687"
                },
                "isDefault": true,
                "relationship": "65e8b2e0-db80-480d-a43d-f1682c8e15e5"
              }
            ]
          },
          {
            "name": "sit_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9569c823-1f14-4767-a48c-a8c211f9198a",
            "sourceColumn": "sit_turma",
            "summarizeBy": "none"
          },
          {
            "name": "instituicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d11db63-9f49-4343-810b-52f3ae6bd423",
            "sourceColumn": "instituicao",
            "summarizeBy": "none"
          },
          {
            "name": "municipio_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b382d73c-d433-41b4-8762-3e41ab0dda72",
            "sourceColumn": "municipio_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "uf_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae8e6857-fc0a-4f89-a9ca-fe390dd80ff9",
            "sourceColumn": "uf_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8abf083-f621-48fa-b2d7-22d32b532e43",
            "sourceColumn": "conteudista",
            "summarizeBy": "none"
          },
          {
            "name": "tematica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b90764d-e1e3-42d7-9c4b-43cb960526ed",
            "sourceColumn": "tematica",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddd9fbe5-331f-462f-8320-dbdefd15a34c",
            "sourceColumn": "codigo_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fed7e00-433f-44ea-a959-6f2dd6b861d9",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a770c629-4cc0-42d6-9e24-78a9fd29af59",
            "sourceColumn": "idade",
            "summarizeBy": "sum"
          },
          {
            "name": "sit_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d541a777-a3a5-4c47-96bb-8b923a9fa039",
            "sourceColumn": "sit_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00c4783e-98cc-46af-8f2d-dfdc8899443f",
            "sourceColumn": "poder",
            "summarizeBy": "none"
          },
          {
            "name": "esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "481a59b9-ca50-4bcb-b4a1-c3b01c2f7f97",
            "sourceColumn": "esfera",
            "summarizeBy": "none"
          },
          {
            "name": "email_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b9e76a-9a1e-425e-8ba7-e37be3700f9f",
            "sourceColumn": "email_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "telefone_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df49ec45-c688-4045-96e3-286d74b66807",
            "sourceColumn": "telefone_pessoa",
            "summarizeBy": "sum"
          },
          {
            "name": "email_conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "101eb44a-9c47-4fbf-b87f-bab7eb61dc62",
            "sourceColumn": "email_conteudista",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7095fe4e-ae73-49a3-9751-d9d393a0ea19",
        "partitions": [
          {
            "name": "sample_evg_enriquecido",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\sophia.silva\\Downloads\\sample_evg_enriquecido.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Tipo Alterado\", {{\"dt_matricula\", each Text.BeforeDelimiter(Text.From(_, \"pt-BR\"), \" \"), type text}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Texto Extraído Antes do Delimitador\",{{\"dt_matricula\", type date}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado1\", {\"cod_turma\"}, Dim_turma, {\"cod_turma\"}, \"Dim_turma\", JoinKind.LeftOuter)",
                "in",
                "    #\"Consultas Mescladas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0dc8cf17-a3e4-48ac-9adc-4be558576be6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5b89879f-a8a5-4de7-b758-6466d0550366",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4171ab01-526c-4170-82df-713425af501c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "153cf2c7-7ccb-4704-890f-f45068327b5e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "25cf929e-cae1-4724-9d9e-34cd6688a8df",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6f4c71e2-5e4c-4fbf-9b37-52369d387639",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f044bcff-77e3-4faa-8d66-eb697f2ac5be",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9cba1433-36ad-414a-a6e2-4e16d07b80aa",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "838b6fcd-6321-4f22-855c-4a3b6efcb574",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3b8f5b87-1fe5-45ec-8622-bb566033472f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "9837bf40-384e-4f80-a002-40ee1d82a7b5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "96121f6e-d6b0-4559-922b-1abc96496bb4",
                "ordinal": 3
              }
            ],
            "lineageTag": "ea922e58-14c8-40bc-b2ba-27bc3f35bdf9"
          }
        ],
        "isHidden": true,
        "lineageTag": "5dc7a6c9-aa0e-4dc8-a2f9-bef87ea48ad6",
        "partitions": [
          {
            "name": "LocalDateTable_0dc8cf17-a3e4-48ac-9adc-4be558576be6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('sample_evg_enriquecido'[dt_matricula])), 1, 1), Date(Year(MAX('sample_evg_enriquecido'[dt_matricula])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e5b7cfce-ccad-4ec6-acff-3739d4d4d687",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6f3f2ae9-ada9-4e27-8cc9-bf88aa7cf34c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7016b86f-9607-4067-a0c9-b2b760e88dd6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "07864eae-adb4-43a0-9d56-2d30301b7e5c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "fb0ac8a0-bf6f-4f82-9865-7c1b48dd1867",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0b7581ca-90e0-4963-a7ed-9b9e4bbf9894",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "989662f5-e109-4df1-9eca-1f7ef96e35cf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "929a8b4d-604b-45b2-a349-2ea9620c21eb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f102af96-7416-4c05-ad70-63f071c66afa",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "47912df7-a0b1-4b61-939a-08560cce1118",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "8c8ab883-f035-47c6-bf98-65cb03f573c2",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "569f45da-bcfa-48fc-83bb-8a3e6d73f47e",
                "ordinal": 3
              }
            ],
            "lineageTag": "90bbd26a-d9ff-4953-a6b9-088ed7e2a4cd"
          }
        ],
        "isHidden": true,
        "lineageTag": "1c698c10-434d-49f3-969e-cd59f95d9372",
        "partitions": [
          {
            "name": "LocalDateTable_e5b7cfce-ccad-4ec6-acff-3739d4d4d687",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('sample_evg_enriquecido'[dt_fim])), 1, 1), Date(Year(MAX('sample_evg_enriquecido'[dt_fim])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim_Calendario",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b4bb3d80-3fb6-4660-b9d7-4519899a4ff8",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_bbaeb3f6-cc6a-4434-a8e4-e5aaba71dfd1"
                },
                "isDefault": true,
                "relationship": "3cf1f448-4648-4b7e-825a-116fcc2d35e5"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "181c72fc-6977-41dd-8ddf-9fe0517bc80b",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4506b8bf-738a-49c7-804d-3d5350981f90",
            "sourceColumn": "Nome do Mês",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cca32ac4-8def-4a18-b854-9eca1dcc1f52",
        "partitions": [
          {
            "name": "Dim_Calendario",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = \"\",",
                "    DtMin = List.Min(sample_evg_enriquecido[dt_matricula]),",
                "    DtMax = List.Max(sample_evg_enriquecido[dt_matricula]),",
                "    QtdDias = Duration.Days(DtMax - DtMin)+1,",
                "    Personalizar1 = List.Dates(DtMin, QtdDias, #duration(1,0,0,0)),",
                "    #\"Convertido para Tabela\" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"Data\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"Data\", type date}}),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Tipo Alterado\", \"Ano\", each Date.Year([Data]), Int64.Type),",
                "    #\"Nome do Mês Inserido\" = Table.AddColumn(#\"Ano Inserido\", \"Nome do Mês\", each Date.MonthName([Data]), type text),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Nome do Mês Inserido\",{{\"Ano\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bbaeb3f6-cc6a-4434-a8e4-e5aaba71dfd1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "40cc0486-cf36-4411-88ac-6c345e3431f1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "de2bf046-c78a-4ef3-8c21-862fe9b76da6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bfb31605-7480-4d15-be3e-b3e58e27cdaf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2b5eaea2-240d-42fe-b9d2-f9a4561b745b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dfe9699c-2761-43aa-a87a-b943b4c653f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "27f76a78-8320-4c32-979a-ef7788dab126",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ecbbb67e-767e-4473-a882-a7731e798b4a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "88bba5d2-2e2f-44fe-9206-8e77843468c2",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "8d44c042-3de3-4338-8df3-e43ca9f7f867",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "5625e736-24b5-4368-afbc-bcbaa3f587b6",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "9b1a4668-326d-40e1-bef6-6601311bd4be",
                "ordinal": 3
              }
            ],
            "lineageTag": "9da39d4f-64d4-4880-97a7-ef7190bfb462"
          }
        ],
        "isHidden": true,
        "lineageTag": "b5dfa0a1-b422-4a48-961e-e17376e496b1",
        "partitions": [
          {
            "name": "LocalDateTable_bbaeb3f6-cc6a-4434-a8e4-e5aaba71dfd1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim_Calendario'[Data])), 1, 1), Date(Year(MAX('Dim_Calendario'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim_Curso",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nome_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18c82547-e4d9-43db-aa1d-88218de9e2ae",
            "sourceColumn": "nome_curso",
            "summarizeBy": "none"
          },
          {
            "name": "carga_horaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57184d88-3821-4c83-babb-00f294a447e5",
            "sourceColumn": "carga_horaria",
            "summarizeBy": "sum"
          },
          {
            "name": "instituicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20952b90-2964-4ba2-ab9a-f9493f58783e",
            "sourceColumn": "instituicao",
            "summarizeBy": "none"
          },
          {
            "name": "SK_Curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b4e2393-6daa-4ac4-a58b-aa1123b64d93",
            "sourceColumn": "SK_Curso",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7586d31a-bae5-47bf-9f7a-28844ff08e9c",
        "partitions": [
          {
            "name": "Dim_Curso",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\sophia.silva\\Downloads\\sample_evg_enriquecido.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Tipo Alterado\", {{\"dt_matricula\", each Text.BeforeDelimiter(Text.From(_, \"pt-BR\"), \" \"), type text}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Texto Extraído Antes do Delimitador\",{{\"dt_matricula\", type date}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Tipo Alterado1\",{\"nome_curso\", \"carga_horaria\", \"instituicao\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Duplicatas Removidas\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"SK_Curso\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Aluno",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a23c0112-e176-40f7-bad8-b04c0f44d8bc",
            "sourceColumn": "cod_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "uf_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41f20df8-c398-4b17-8ea7-f6227836338b",
            "sourceColumn": "uf_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13f13bcd-1a86-4c44-8883-77b1ce003aea",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "SK_Aluno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0bbe475a-777f-4ceb-8a8e-6f46089b392b",
            "sourceColumn": "SK_Aluno",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "99d5395a-1015-441f-bc96-561fdcba83ab",
        "partitions": [
          {
            "name": "Dim_Aluno",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\sophia.silva\\Downloads\\sample_evg_enriquecido.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Tipo Alterado\", {{\"dt_matricula\", each Text.BeforeDelimiter(Text.From(_, \"pt-BR\"), \" \"), type text}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Texto Extraído Antes do Delimitador\",{{\"dt_matricula\", type date}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Tipo Alterado1\",{\"cod_matricula\", \"uf_pessoa\", \"sexo\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Duplicatas Removidas\", \"Índice\", 0, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"SK_Aluno\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_turma",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dt_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c58755dd-4f30-4a03-8a1e-029b9018a63b",
            "sourceColumn": "dt_matricula",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_d8f42845-b91c-4467-8bef-7eb5b34c3e41"
                },
                "isDefault": true,
                "relationship": "b71677c1-ba5d-47f8-a27d-0f6b21b20f9c"
              }
            ]
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "863d6ef5-a02e-415d-be2a-cda309d7f5a4",
            "sourceColumn": "cod_turma",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aa04264-1edb-4a5a-b5b0-ca019ad1890d",
            "sourceColumn": "nome_turma",
            "summarizeBy": "none"
          },
          {
            "name": "modalidade_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7342726-6935-482a-81db-4528956b2640",
            "sourceColumn": "modalidade_turma",
            "summarizeBy": "none"
          },
          {
            "name": "sit_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64a44333-6328-40e9-849e-4770ed01e7b8",
            "sourceColumn": "sit_turma",
            "summarizeBy": "none"
          },
          {
            "name": "Sk_Turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60276b5c-3a89-4fcb-98b4-83b5658340ac",
            "sourceColumn": "Sk_Turma",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "57fc8c72-5ec6-42e5-85b4-590099e0fd48",
        "partitions": [
          {
            "name": "Dim_turma",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\sophia.silva\\Downloads\\sample_evg_enriquecido.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Tipo Alterado\", {{\"dt_matricula\", each Text.BeforeDelimiter(Text.From(_, \"pt-BR\"), \" \"), type text}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Texto Extraído Antes do Delimitador\",{{\"dt_matricula\", type date}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Tipo Alterado1\",{\"dt_matricula\", \"cod_turma\", \"nome_turma\", \"modalidade_turma\", \"sit_turma\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Duplicatas Removidas\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"Sk_Turma\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d8f42845-b91c-4467-8bef-7eb5b34c3e41",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bd99ee9e-18d0-4e1f-9746-d3e5f7bfea99",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "72340b82-c23a-42b4-bc67-63a146b96aa7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e19f61b9-a802-4412-97b5-ea6ba4c6ba1f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e561c3ed-a7ef-4524-80ab-a9b358a706b5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6c20739e-4178-491a-be4a-d8b02fc84135",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e6641229-8742-43cf-94d7-56b4ab7370cf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4c410f99-d2f1-4cf2-abd9-25ab8aaabb52",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f2d424d5-4ae1-497b-91cc-6319d2b05a29",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "da5b2974-9be5-4b76-b85f-0bf91af90288",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e418fed5-6666-4c73-9813-07dbf2934e5e",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "03d9e51f-72a6-479c-88c3-464740853949",
                "ordinal": 3
              }
            ],
            "lineageTag": "139859e8-9836-42d6-b1d7-71e2d3d72499"
          }
        ],
        "isHidden": true,
        "lineageTag": "0724e523-2912-429b-99b2-bd31ad8a7cd5",
        "partitions": [
          {
            "name": "LocalDateTable_d8f42845-b91c-4467-8bef-7eb5b34c3e41",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim_turma'[dt_matricula])), 1, 1), Date(Year(MAX('Dim_turma'[dt_matricula])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}